version: 2.1
jobs:
  build:
    docker:
      - image: node:12.18.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-
      - run: yarn install

      - save_cache:
        paths:
          - node_modeules
        key: v1-dependencies-{{ checksum "package.json"}}

      - run: yarn test
      - run: yarn build
      - run: yarn deploy
