version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-
      - run: yarn install

      - run: yarn run build

      - save_cache:
          paths:
             - node_modeules
          key: v1-dependencies-{{ checksum "package.json"}}
          
      - run: yarn deploy
