version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-
      - run: yarn install      
      - run: npx browserslist --update-db
      - run: yarn build 
      
      - save_cache:
          paths:
             - node_modeules
          key: v1-dependencies-{{ checksum "package.json"}}

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AKIA2BHZH37CGPUFAOJA
          aws-secret-access-key: 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
          from: build/
          to: 's3://react-yanwu-aws-host'
        
orbs:
  aws-s3: circleci/aws-s3@2.0.0

